### ISSUE TITLE
Telia Play datetime error

### ISSUE THREAD

**Issue by Mariusz89B** [Mariusz89B/script.mtvguide#5]
### Describe the bug
Here is a clear and concise description of what the problem is:
Attribute error.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Need fix.

## Actual Behavior
Correct attribute.

## Possible Fix
N/A

### To Reproduce
1. Threading loop.

### Debuglog
`2021-04-19 16:54:01.476 T:11008   ERROR <general>: Thread-13
2021-04-19 16:54:01.476 T:11008   ERROR <general>: :
                                                   
2021-04-19 16:54:01.476 T:11008   ERROR <general>: Traceback (most recent call last):
                                                   
2021-04-19 16:54:01.476 T:11008   ERROR <general>:   File "/mnt/expand/cc620f21-de0f-42b0-8ad3-7cf00e025b68/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2021-04-19 16:54:01.477 T:11008   ERROR <general>:     
2021-04-19 16:54:01.478 T:11008   ERROR <general>: self.run()
2021-04-19 16:54:01.478 T:11008   ERROR <general>: 
                                                   
2021-04-19 16:54:01.478 T:11008   ERROR <general>:   File "/mnt/expand/cc620f21-de0f-42b0-8ad3-7cf00e025b68/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 870, in run
                                                   
2021-04-19 16:54:01.479 T:11008   ERROR <general>:     
2021-04-19 16:54:01.479 T:11008   ERROR <general>: self._target(*self._args, **self._kwargs)
2021-04-19 16:54:01.479 T:11008   ERROR <general>: 
                                                   
2021-04-19 16:54:01.479 T:11008   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.mtvguide/teliaplaycids.py", line 114, in run
                                                   
2021-04-19 16:54:01.487 T:11008   ERROR <general>:     
2021-04-19 16:54:01.488 T:11008   ERROR <general>: ab = TeliaPlayUpdater().checkRefresh()
2021-04-19 16:54:01.488 T:11008   ERROR <general>: 
                                                   
2021-04-19 16:54:01.488 T:11008   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.mtvguide/teliaplaycids.py", line 419, in checkRefresh
                                                   
2021-04-19 16:54:01.489 T:11008   ERROR <general>:     
2021-04-19 16:54:01.489 T:11008   ERROR <general>: self.validTo = datetime.datetime.now() - timedelta(days=1)
2021-04-19 16:54:01.489 T:11008   ERROR <general>: 
                                                   
2021-04-19 16:54:01.489 T:11008   ERROR <general>: AttributeError
2021-04-19 16:54:01.489 T:11008   ERROR <general>: : 
2021-04-19 16:54:01.491 T:11008   ERROR <general>: type object 'datetime.datetime' has no attribute 'datetime'
2021-04-19 16:54:01.491 T:11008   ERROR <general>: `

### Screenshots 
Here are some links or screenshots to help explain the problem:
N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
N/A

### Your Environment
Used Operating system:
 - [x] Android
 - [x] iOS
 - [x] tvOS
 - [x] Linux
 - [x] OSX
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version: All

**Comment by Mariusz89B** [comment]
Error resolved in https://github.com/Mariusz89B/script.mtvguide/commit/05eb26d13350401339e8721f55b58fcac865ca71
